In [2]:
import pandas as pd

In [9]:
df = pd.read_csv(r'C:\Users\ellah\OneDrive\Data Science Projects\overdose-data-us\VSRR_Provisional_Drug_Overdose_Death_Counts.csv')

In [10]:
df.head()

,State,Year,Month,Period,Indicator,Data Value,Percent Complete,Percent Pending Investigation,State Name,Footnote,Footnote Symbol,Predicted Value
0,AK,2015,January,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
1,AK,2015,February,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
2,AK,2015,March,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
3,AK,2015,April,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN
4,AK,2015,May,12 month-ending,Cocaine (T40.5),NaN,100,0.0,Alaska,Numbers may differ from published reports usin...,**,NaN

In [11]:
df["State"].nunique()

54

In [12]:
df.shape

(78120, 12)

In [13]:
df.columns

Index(['State', 'Year', 'Month', 'Period', 'Indicator', 'Data Value',
       'Percent Complete', 'Percent Pending Investigation', 'State Name',
       'Footnote', 'Footnote Symbol', 'Predicted Value'],
      dtype='object')

In [14]:
df['Indicator'].value_counts()

Indicator
Number of Deaths                                                               6696
Percent with drugs specified                                                   6696
Number of Drug Overdose Deaths                                                 6696
Cocaine (T40.5)                                                                6448
Natural & semi-synthetic opioids (T40.2)                                       6448
Methadone (T40.3)                                                              6448
Heroin (T40.1)                                                                 6448
Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)    6448
Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)               6448
Opioids (T40.0-T40.4,T40.6)                                                    6448
Psychostimulants with abuse potential (T43.6)                                  6448
Synthetic opioids, excl. methadone (T40.4)                                     6448
Name: count, dtype: int64

In [15]:
df = df[~df['Indicator'].isin(['Number of Deaths', 'Percent with drugs specified', 'Number of Drug Overdose Deaths'])]

In [16]:
df.shape

(58032, 12)

In [17]:
df['Indicator'] = df['Indicator'].replace({
    'Methadone (T40.3)':'Methadone',
    'Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)':'Methadone',
    'Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)':'Methadone'
})

df['Indicator'] = df['Indicator'].replace({
    'Natural & semi-synthetic opioids (T40.2)':'Opioids',
    'Opioids (T40.0-T40.4,T40.6)':'Opioids',
    'Synthetic opioids, excl. methadone (T40.4)':'Opioids'
})

df['Indicator'] = df['Indicator'].replace({
    'Cocaine (T40.5)':'Cocaine',
    'Heroin (T40.1)':'Heroin',
    'Psychostimulants with abuse potential (T43.6)':'Psychostimulants'
})

In [18]:
df['Indicator'].value_counts()

Indicator
Methadone           19344
Opioids             19344
Cocaine              6448
Heroin               6448
Psychostimulants     6448
Name: count, dtype: int64

In [19]:
df.isna().sum()

State                                0
Year                                 0
Month                                0
Period                               0
Indicator                            0
Data Value                       14293
Percent Complete                     0
Percent Pending Investigation        0
State Name                           0
Footnote                             0
Footnote Symbol                      0
Predicted Value                  14242
dtype: int64

In [20]:
df['Data Value'].value_counts()

Data Value
32       240
27       238
28       236
29       223
31       220
        ...
2,544      1
2,686      1
2,685      1
2,755      1
2,719      1
Name: count, Length: 4567, dtype: int64

In [21]:
df.drop(['Data Value', 'Predicted Value'], axis=1, inplace=True)

In [22]:
df.head()

,State,Year,Month,Period,Indicator,Percent Complete,Percent Pending Investigation,State Name,Footnote,Footnote Symbol
0,AK,2015,January,12 month-ending,Cocaine,100,0.0,Alaska,Numbers may differ from published reports usin...,**
1,AK,2015,February,12 month-ending,Cocaine,100,0.0,Alaska,Numbers may differ from published reports usin...,**
2,AK,2015,March,12 month-ending,Cocaine,100,0.0,Alaska,Numbers may differ from published reports usin...,**
3,AK,2015,April,12 month-ending,Cocaine,100,0.0,Alaska,Numbers may differ from published reports usin...,**
4,AK,2015,May,12 month-ending,Cocaine,100,0.0,Alaska,Numbers may differ from published reports usin...,**

In [24]:
df['Percent Pending Investigation'].value_counts()

Percent Pending Investigation
0.000000    7443
0.020793      18
0.008805      18
0.008415      18
0.035356      18
            ...
0.285906       9
0.421300       9
0.590863       9
0.794795       9
0.069946       9
Name: count, Length: 5591, dtype: int64

In [25]:
df['Percent Complete'].value_counts()

Percent Complete
100    58032
Name: count, dtype: int64

In [26]:
df.drop(['Percent Complete'], axis=1, inplace=True)

In [27]:
df.head()

,State,Year,Month,Period,Indicator,Percent Pending Investigation,State Name,Footnote,Footnote Symbol
0,AK,2015,January,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...,**
1,AK,2015,February,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...,**
2,AK,2015,March,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...,**
3,AK,2015,April,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...,**
4,AK,2015,May,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...,**

In [28]:
df['Footnote Symbol'].value_counts()

Footnote Symbol
**    50544
*      7488
Name: count, dtype: int64

In [30]:
df.drop(['Footnote Symbol'], axis=1, inplace=True)

In [31]:
df.head()

,State,Year,Month,Period,Indicator,Percent Pending Investigation,State Name,Footnote
0,AK,2015,January,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
1,AK,2015,February,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
2,AK,2015,March,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
3,AK,2015,April,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
4,AK,2015,May,12 month-ending,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...

In [32]:
df['Period'].value_counts()

Period
12 month-ending    58032
Name: count, dtype: int64

In [33]:
df.drop(['Period'], axis=1, inplace=True)

In [34]:
df.head()

,State,Year,Month,Indicator,Percent Pending Investigation,State Name,Footnote
0,AK,2015,January,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
1,AK,2015,February,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
2,AK,2015,March,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
3,AK,2015,April,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...
4,AK,2015,May,Cocaine,0.0,Alaska,Numbers may differ from published reports usin...